# Generated by Django 4.2.6 on 2023-10-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wyk_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Wykrojniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('wyk_kod', models.CharField(max_length=16)),
                ('wyk_size', models.CharField(help_text='wymiary w milimetrach', max_length=12)),
                ('wyk_image', models.ImageField(blank=True, upload_to='wykrojniki_img/')),
                ('wyk_pdf', models.FileField(blank=True, upload_to='wykrojniki_pdf/')),
                ('wyk_cdr', models.FileField(blank=True, upload_to='wykrojniki_cdr/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
