# Generated by Django 4.2.6 on 2023-10-25 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wydruki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=80)),
                ('klient', models.CharField(max_length=80)),
                ('wyd_roz_sze', models.DecimalField(decimal_places=2, help_text='szerokość w mm', max_digits=10)),
                ('wyd_roz_wys', models.DecimalField(decimal_places=2, help_text='wysokość w mm', max_digits=10)),
                ('wyd_zamówienie', models.IntegerField(default=0)),
                ('wyd_wykonane', models.IntegerField(default=0)),
                ('wyd_gotowe', models.BooleanField(default=False)),
                ('wyd_plan_date', models.DateField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
